on:
  page_build:
  schedule:
    - cron: "0 0 * * *"
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: "https://trevordmiller.com"
          configPath: "./.github/config/audit-production.json"
          temporaryPublicStorage: true
          runs: 3
