on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./.github/config/audit-local.json"
          temporaryPublicStorage: true
          runs: 3
      - name: Links
        uses: peter-evans/link-checker@v1
        id: lc
        with:
          args: --document-root . --verbose --recursive *
      - name: Exit
        run: exit ${{ steps.lc.outputs.exit_code }}
