name: Push
on: push
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./.github/config/local/lighthouserc.json"
          temporaryPublicStorage: true
          runs: 3
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Links
        uses: peter-evans/link-checker@v1
        id: lc
        with:
          args: -v -r *
      - name: Exit
        run: exit ${{ steps.lc.outputs.exit_code }}
